const gulp = require("gulp");

const run = require("gulp-run-command").default;

gulp.task("bundle-js", function () {
    const glob = require("glob");
    const browserify = require("browserify");
    const tsify = require("tsify");
    const fancy_log = require("fancy-log");
    const source = require("vinyl-source-stream");
    const buffer = require("vinyl-buffer");
    const sourcemaps = require("gulp-sourcemaps");
    const uglify = require("gulp-uglify");

    var files = glob.sync('./src/**/*.ts');

    return browserify({ // Collect js dependencies
        basedir: ".",
        debug: true,
        entries: files,//["src/main.ts"],
        cache: {},
        packageCache: {},
    })
        .plugin(tsify) // Compile typescript
        .bundle()
        .on("error", fancy_log)
        .pipe(source("bundle.js")) //Collect in bundle.js
        .pipe(buffer())
        .pipe(sourcemaps.init({ loadMaps: true })) // Collect source maps before uglifying
        // TODO: for some reason meter_chart_change_time gets removed by the default config
        // This config costs about 5kb
        .pipe(
            uglify(/*{
                compress: { unused: false },
                mangle: { reserved: ["meter_chart_change_time"] },
            }*/)
        )
        .pipe(sourcemaps.write("./"))
        .pipe(gulp.dest("assets/js")); // Write to assets/js/bundle.js(.map)
});

// Write minified html to assets/index.html
gulp.task("copy-html", function () {
    const htmlmin = require("gulp-html-minifier-terser");
    const inlineimg = require('gulp-inline-image-html');

    return gulp
        .src(["src/index.html"])
        .pipe(inlineimg('src'))
        .pipe(
            htmlmin({
                collapseBooleanAttributes: true,
                collapseInlineTagWhitespace: true,
                collapseWhitespace: true,
                conservativeCollapse: true,
                decodeEntities: true,
                includeAutoGeneratedTags: false,
                minifyCSS: true,
                minifyJS: true,
                minifyURLs: true,
                preventAttributesEscaping: true,
                processConditionalComments: true,
                removeAttributeQuotes: true,
                removeComments: true,
                removeEmptyAttributes: true,
                removeOptionalTags: true,
                removeRedundantAttributes: true,
                removeScriptTypeAttributes: true,
                removeStyleLinkTypeAttributes: true,
                sortAttributes: true,
                sortClassName: true,
                trimCustomFragments: true,
                useShortDoctype: true,
            })
        )
        .pipe(gulp.dest("assets"));
});

gulp.task("sass", function () {
    const sass = require("gulp-sass");
    const purgecss = require("gulp-purgecss");
    const postcss = require("gulp-postcss");
    const autoprefixer = require("autoprefixer");
    const cssnano = require("cssnano");

    return gulp
        .src("src/scss/*.scss")
        .pipe(sass()) // Compile sass to css
        /*.pipe(purgecss({ //remove unused css
              content: ["src/*.html"],
              whitelistPatterns: [/^btn-/]
          }))*/
        .pipe(
            postcss([
                autoprefixer(), // Add browser-specific prefixes
                cssnano({ // Minify css
                    preset: "advanced",
                }),
            ])
        )
        .pipe(gulp.dest("assets/css")); // Write to assets/css/main.css
});

// Embed css and js into html
gulp.task("embed", run("python embed_css_and_js.py"));

gulp.task("gzip", function () {
    const gzip = require('gulp-gzip');
    return gulp.src('dist/index.html')
        .pipe(gzip({ gzipOptions: { level: 9 } }))
        .pipe(gulp.dest('dist'));
});

gulp.task("generate_header", run("xxd -i dist/index.html.gz dist/index.html.h"));

gulp.task("patch_header", function() {
    const replace = require('gulp-string-replace');
    return gulp.src("dist/index.html.h")
               .pipe(replace('unsigned char', 'const char'))
               .pipe(replace('dist_index_html_gz', 'index_html_gz'))
               .pipe(gulp.dest("dist"))
});

gulp.task("debug",
    gulp.series(gulp.parallel("copy-html"), gulp.parallel("sass"), "bundle-js")
);

gulp.task("default",
    gulp.series(
        "debug",
        "embed",
        "gzip",
        "generate_header",
        "patch_header",
    )
);
