import type {SidebarsConfig} from '@docusaurus/plugin-content-docs';

/**
 * Creating a sidebar enables you to:
 - create an ordered group of docs
 - render a sidebar for each doc of that group
 - provide next/previous navigation

 The sidebars can be generated from the filesystem, or explicitly defined here.

 Create as many sidebars as you want.
 */
const sidebars: SidebarsConfig = {
  // By default, Docusaurus generates a sidebar from the docs folder structure
  //sidebar: [{type: 'autogenerated', dirName: '.'}],

  // But you can create a sidebar manually

  sidebar: [
    'home',
    {
      type: 'category',
      label: 'WARP Charger',
      items: [
        {
          type: 'autogenerated',
          dirName: 'warp_charger',
	      },
        {
          type: 'link',
          label: 'Dokumente',
          href: 'https://warp-charger.com/downloads/#documents-warp3',
          key: 'warp-charger-documents',
        },
        {
          type: 'link',
          label: 'Firmwares',
          href: 'https://warp-charger.com/downloads/#firmwares-warp3',
          key: 'warp-charger-firmwares',
        },
      ],
    },
    {
      type: 'category',
      label: 'WARP Energy Manager',
      items: [
        {
          type: 'autogenerated',
          dirName: 'warp_energy_manager',
	      },
        {
          type: 'link',
          label: 'Dokumente',
          href: 'https://warp-charger.com/downloads/#documents-wem',
          key: 'energy-manager-documents',
        },
        {
          type: 'link',
          label: 'Firmwares',
          href: 'https://warp-charger.com/downloads/#firmwares-wem',
          key: 'energy-manager-firmwares',
        },

      ]
    },
    {
      type: 'category',
      label: 'WARP Ladesäule',
      items: [
        {
          type: 'autogenerated',
          dirName: 'warp_ladesäule',
	      },
        {
          type: 'link',
          label: 'Dokumente',
          href: 'https://warp-charger.com/downloads/#documents-stands',
          key: 'ladesauele-documents',
        },
      ]
    },
{
      type: 'category',
      label: 'Tutorials',
      items: [
        {
          type: 'autogenerated',
          dirName: 'tutorials',
	      },

      ]
    },

    {
      type: 'category',
      label: 'Webinterface',
      items: [
        {
          type: 'autogenerated',
          dirName: 'webinterface',
	      },

      ]
    },
    {
      type: 'category',
      label: 'Schnittstellen',
      key: 'interfaces-category',
      items: [
        {
          type: 'autogenerated',
          dirName: 'interfaces',
	      }
      ]
    },
    {
      type: 'category',
      label: 'Smart Home',
      items: [
        {
          type: 'autogenerated',
          dirName: 'smart_home',
	      }
      ]
    },
	{
      type: 'category',
      label: 'Kompatible Geräte',
      items: [
        {
          type: 'autogenerated',
          dirName: 'compatible_devices',
	      }
      ]
    },

    'faq',
  ],
};

export default sidebars;
