import type {SidebarsConfig} from '@docusaurus/plugin-content-docs';

/**
 * Creating a sidebar enables you to:
 - create an ordered group of docs
 - render a sidebar for each doc of that group
 - provide next/previous navigation

 The sidebars can be generated from the filesystem, or explicitly defined here.

 Create as many sidebars as you want.
 */
const sidebars: SidebarsConfig = {
  // By default, Docusaurus generates a sidebar from the docs folder structure
  //sidebar: [{type: 'autogenerated', dirName: '.'}],

  // But you can create a sidebar manually

  sidebar: [
    'home',
    {
      type: 'category',
      label: 'WARP Charger',
      items: [
        {
          type: 'autogenerated',
          dirName: 'warp_charger',
	      },
        {
          type: 'link',
          label: 'Firmwares',
          href: 'https://warp-charger.com/downloads/#firmwares-warp3',
        },
      ],
    },
    {
      type: 'category',
      label: 'WARP Energy Manager',
      items: [
        {
          type: 'autogenerated',
          dirName: 'warp_energy_manager',
	      },
        {
          type: 'link',
          label: 'Firmwares',
          href: 'https://warp-charger.com/downloads/#firmwares-wem',
        },
      ]
    },
    {
      type: 'category',
      label: 'WARP Ladesäule',
      items: [
        {
          type: 'autogenerated',
          dirName: 'warp_ladesäule',
	      },
      ]
    },
    {
      type: 'category',
      label: 'MQTT und HTTP API',
      items: [
        {
          type: 'autogenerated',
          dirName: 'mqtt_http',
	      }
      ]
    },
    {
      type: 'category',
      label: 'Modbus',
      items: [
        {
          type: 'autogenerated',
          dirName: 'modbus',
	      }
      ]
    },
    'evcc',
    'remote_access',
    'compatible_meters',
    'faq',
    {
      type: 'link',
      label: 'PDF-Dokumente',
      href: 'https://warp-charger.com/downloads/#documents',
    },
  ],
};

export default sidebars;
