import type {SidebarsConfig} from '@docusaurus/plugin-content-docs';

type DocLink = {label: string; href: string; key: string};
type Device = {label: string; dirName: string; documentLinks: DocLink[]};

// Builds the "documents" and "firmwares" download links for a device. The
// `{locale}` placeholder is replaced with the active locale (de/en) at render
// time in src/theme/DocSidebarItems.
function downloadLinks(id: string): DocLink[] {
  const base = 'https://warp-charger.com/{locale}/software/downloads';
  return [
    {label: 'Dokumente', href: `${base}#documents-${id}`, key: `${id}-documents`},
    {label: 'Firmwares', href: `${base}#firmwares-${id}`, key: `${id}-firmwares`},
  ];
}

// WARP Charger generations.
const WARP1: Device = {label: 'WARP1 Charger', dirName: 'warp1', documentLinks: downloadLinks('warp1')};
const WARP2: Device = {label: 'WARP2 Charger', dirName: 'warp2', documentLinks: downloadLinks('warp2')};
const WARP3: Device = {label: 'WARP3 Charger', dirName: 'warp3', documentLinks: downloadLinks('warp3')};
const WARP4: Device = {label: 'WARP4 Charger', dirName: 'warp4', documentLinks: downloadLinks('warp4')};

// WARP Energy Manager generations.
const WEM1: Device = {label: 'WARP Energy Manager 1.0', dirName: 'wem1', documentLinks: downloadLinks('wem1')};
const WEM2: Device = {label: 'WARP Energy Manager 2.0', dirName: 'wem2', documentLinks: downloadLinks('wem2')};

// A device category: the device's own manual pages plus its download links. The
// generation can be switched via the device switcher injected by
// src/theme/DocSidebarItems (see src/components/DeviceSwitcherMenu).
function deviceCategory(device: Device) {
  return {
    type: 'category',
    label: device.label,
    collapsed: true,
    items: [
      {type: 'autogenerated', dirName: device.dirName},
      ...device.documentLinks.map((l) => ({type: 'link', ...l})),
    ],
  };
}

 // Shared documentation sections that appear in every per-device sidebar so that
 // the full documentation stays reachable regardless of the selected device. The
 // WARP Energy Manager generation shown here (`wem`) is switchable; it defaults
 // to WARP Energy Manager 2.0.
function sharedSections(wem: Device) {
  return [
    deviceCategory(wem),
    {
      type: 'category',
      label: 'WARP Ladesäule',
      items: [
        {type: 'autogenerated', dirName: 'warp_ladesäule'},
        {
          type: 'link',
          label: 'Dokumente',
          href: 'https://warp-charger.com/{locale}/software/downloads#documents-stands',
          key: 'ladesauele-documents',
        },
      ],
    },
    {
      type: 'category',
      label: 'Tutorials',
      items: [{type: 'autogenerated', dirName: 'tutorials'}],
    },
    {
      type: 'category',
      label: 'Webinterface',
      items: [{type: 'autogenerated', dirName: 'webinterface'}],
    },
    {
      type: 'category',
      label: 'Schnittstellen',
      key: 'interfaces-category',
      items: [{type: 'autogenerated', dirName: 'interfaces'}],
    },
    {
      type: 'category',
      label: 'Smart Home',
      items: [{type: 'autogenerated', dirName: 'smart_home'}],
    },
    {
      type: 'category',
      label: 'Kompatible Geräte',
      items: [{type: 'autogenerated', dirName: 'compatible_devices'}],
    },
    'faq',
  ];
}

// A full sidebar: a primary device category on top, followed by the shared
// sections (which include the WARP Energy Manager and WARP Ladesäule).
function fullSidebar(primary: Device, wem: Device) {
  return ['home', deviceCategory(primary), ...sharedSections(wem)];
}

const sidebars: SidebarsConfig = {
  // A doc that belongs to multiple sidebars (the shared sections appear in every
  // sidebar) is assigned to the last sidebar that contains it. The default
  // context for shared pages must therefore be registered last.
  warp1: fullSidebar(WARP1, WEM2),
  warp2: fullSidebar(WARP2, WEM2),
  warp3: fullSidebar(WARP3, WEM2),
  warp4: fullSidebar(WARP4, WEM2),
  // Energy Manager contexts use WARP4 as the default charger and switch the WEM
  // generation.
  wem1: fullSidebar(WARP4, WEM1),
  wem2: fullSidebar(WARP4, WEM2),
};

export default sidebars;
